package com.mediscreen.historymicroservice.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

/**
 *  Class allowing the link with the PatientHistory table of the database
 *  mongoDB named mediscreen
 *  This class represents the history of a note from a doctor on a patient
 */

@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "patienthistory")
public class PatientHistory {
    /**
     *  Id generated by mongoDB
     */
    @Id
    private String id;
    /**
     * Id of Patient
     */
    private Integer patientId;
    /**
     * Date Local
     */
    private LocalDate date;
    /**
     * Annotation written by a doctor on the patient's condition
     */
    private String notes;

}
