package com.mediscreen.historymicroservice.unitaryTest;

import com.mediscreen.historymicroservice.dto.PatientHistoryDTO;
import com.mediscreen.historymicroservice.model.PatientHistory;
import com.mediscreen.historymicroservice.tool.DtoBuilder;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
public class DtoBuilderTest {

    @InjectMocks
    DtoBuilder dtoBuilder;

    //-----------------PatientHistoryDTO---------------------------------------------------------------------------
    @Test
    @DisplayName("PatientHistoryDTO builder Test")
    public void builderPatientHistoryDTOTest(){
        LocalDate date = LocalDate.now();
        PatientHistory ph = new PatientHistory( "id generated by mongoDB", 1, date,
                                                        "a note from a doctor on a patient");
        PatientHistoryDTO phDTO = dtoBuilder.buildPatientHistoryDTO(ph);

        assertThat(phDTO.getId()).isEqualTo(ph.getId());
        assertThat(phDTO.getPatientId()).isEqualTo(ph.getPatientId());
        assertThat(phDTO.getDate()).isEqualTo(ph.getDate());
        assertThat(phDTO.getNotes()).isEqualTo(ph.getNotes());
    }

}
